<a href="https://colab.research.google.com/github/Laiba-Akhtar/Data_Science_and_Analytics_20sw057_task/blob/main/Lab4_57.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
#TASK 1
import numpy as np

# Using the Built-in functions you learned about in the

# previous lesson, create a 4 x 4 ndarray that only

# contains consecutive even numbers from 2 to 32 (inclusive)

X = np.arange(2, 33, 2).reshape(4, 4)

print(X)

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]


In [18]:
#TASK 2
import numpy as np

# Create a 5 x 5 ndarray with consecutive integers from 1 to 25 (inclusive).
array=np.arange(1,26).reshape(5,5)

# Afterwards use Boolean indexing to pick out only the odd numbers in the array
odd_num=array[array%2==1]

# Create a 5 x 5 ndarray with consecutive integers from 1 to 25 (inclusive).

X =np.arange(1,26).reshape(5,5)
print(X)

# Use Boolean indexing to pick out only the odd numbers in the array

Y =array[array%2==1]
print(Y)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[ 1  3  5  7  9 11 13 15 17 19 21 23 25]


In [28]:
#task 3
import numpy as np

# Use Broadcasting to create a 4 x 4 ndarray that has its first
#here broadcasting occur as the numpy expand dimensions

# column full of 1s, its second column full of 2s, its third

# column full of 3s, etc..

X = np.arange(1, 5).reshape(4, 1) * np.ones((1, 4))

print(X)

[[1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]]
